# Default values for reserve.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: reserve-deployment
serviceName: reserve
appLabel: reserve
appName: reserve

replicaCount: 1

image:
  repository: vishalvdev/reserve
  tag: s9

containerPort: 8082

service:
  type: ClusterIP
  port: 8082
  targetPort: 8082

appname_enabled: true
profile_enabled: true
config_enabled: true
eureka_enabled: true
resouceserver_enabled: false
otel_enabled: true
kafka_enabled: true
